name: Update README on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-readme:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create a new branch
        run: |
          git checkout -b update-readme-${{ github.run_id }}

      - name: Append date to README
        run: |
          echo "\nUpdated on $(date +'%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Append current date to README"
          git push origin update-readme-${{ github.run_id }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-readme-${{ github.run_id }}
          commit-message: "Append current date to README"
          title: "Update README with current date"
          body: "Automatically update README with the current date upon PR merge."
          base: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
