name: Update README on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-readme:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create a new branch
        run: |
          git checkout -b update-readme-${{ github.run_id }}

      - name: Append date to README
        run: |
          echo "\nUpdated on $(date +'%Y-%m-%d')" >> README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Append current date to README"

      - name: Push changes
        run: |
          git push origin update-readme-${{ github.run_id }}

      - name: Create pull request
        uses: repo-sync/pull-request@v3
        with:
          source_branch: "update-readme-${{ github.run_id }}"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update README with current date"
          pr_body: "Automatically update README with the current date upon PR merge."
