name: Update README on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the base branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.base.ref }}  # Ensures starting from the base branch

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create a new branch
      run: |
        NEW_BRANCH="update-readme-${{ github.run_id }}"
        git checkout -b $NEW_BRANCH

    - name: Append random integer to README
      run: |
        echo $RANDOM >> README.md

    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Append random integer to README"

    - name: Push new branch
      run: |
        git push origin $NEW_BRANCH

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        PR_TITLE="Update README with random integer"
        PR_BODY="This is an auto-generated PR to update README with a random integer."
        PR_BASE="${{ github.event.pull_request.base.ref }}"
        PR_HEAD="update-readme-${{ github.run_id }}"
        curl \
          -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls" \
          -d '{"title":"'$PR_TITLE'", "body":"'$PR_BODY'", "head":"'$PR_HEAD'", "base":"'$PR_BASE'"}'
