name: Update README on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important to allow history for all branches

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create new branch
      run: git checkout -b update-readme-${{ github.run_id }}

    - name: Append random integer to README
      run: echo $RANDOM >> README.md

    - name: Commit and Push Changes
      run: |
        git add README.md
        git commit -m "Append random integer to README"
        git push origin update-readme-${{ github.run_id }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-readme-${{ github.run_id }}
        title: "Update README with random integer"
        body: "This is an auto-generated PR to update README with a random integer."
        commit-message: "Append random integer to README"
