name: Update README on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "<your-email>"
        git fetch --unshallow

    - name: Create new branch
      run: git checkout -b update-readme-${{ github.run_id }}

    - name: Append random integer to README
      run: echo $RANDOM >> README.md

    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Append random integer to README"

    - name: Push changes
      run: git push origin update-readme-${{ github.run_id }}

    - name: Open a pull request
      uses: repo-sync/pull-request@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: "update-readme-${{ github.run_id }}"
        destination_branch: "main"
        title: "Update README with random integer"
        body: "This is an auto-generated PR to update README with a random integer."
